apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-pd-sc  # I renamed this from 'ebs-sc' to match the cloud provider
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
  fsType: ext4
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
